- name: Generate encryption key and create encryption config for Kubernetes
  hosts: master-1
  tasks:
    - name: Generate an encryption key
      ansible.builtin.shell: head -c 32 /dev/urandom | base64
      register: encryption_key

    - name: Create the encryption-config.yaml file
      ansible.builtin.copy:
        dest: ~/encryption-config.yaml
        content: |
          kind: EncryptionConfig
          apiVersion: v1
          resources:
            - resources:
                - secrets
              providers:
                - aescbc:
                    keys:
                      - name: key1
                        secret: {{ encryption_key.stdout }}
                - identity: {}

- name: Copy encryption config to other masters
  hosts: master-1
  tasks:
    - name: Copy encryption-config.yaml to other master nodes
      ansible.builtin.copy:
        src: ~/encryption-config.yaml
        dest: ~/encryption-config.yaml
      delegate_to: "{{ item }}"
      with_items:
        - master-2

- name: Move encryption-config.yaml to appropriate directory
  hosts: master-1,master-2
  tasks:
    - name: Create /var/lib/kubernetes/ directory
      ansible.builtin.file:
        path: /var/lib/kubernetes/
        state: directory
        owner: root
        group: root
        mode: '0755'
      become: true

    - name: Move encryption-config.yaml to /var/lib/kubernetes/
      ansible.builtin.command:
        cmd: sudo cp /home/pawel/encryption-config.yaml /var/lib/kubernetes/
      become: true
