---
- name: Provision Pod Network
  hosts: master-1
  become: yes
  tasks:
    - name: Apply Flannel CNI manifest
      command: kubectl apply -f https://raw.githubusercontent.com/mmumshad/kubernetes-the-hard-way/master/deployments/coredns.yaml --kubeconfig /home/pawel/admin.kubeconfig

