---
- name: Provision CoreDNS
  hosts: master-1
  become: yes
  tasks:
    - name: Apply CoreDNS manifest
      command: kubectl apply -f https://raw.githubusercontent.com/mmumshad/kubernetes-the-hard-way/master/deployments/coredns.yaml --kubeconfig /home/pawel/admin.kubeconfig

