---
- name: Configure kubectl for Remote Access
  hosts: master-1
  become: yes
  tasks:

    - name: Get kube-api server load-balancer IP
      command: dig +short loadbalancer
      register: loadbalancer_ip

    - name: Generate kubeconfig file for admin user
      block:
        - name: Set Kubernetes cluster
          command: >
            kubectl config set-cluster kubernetes-the-hard-way 
            --certificate-authority=ca.crt 
            --embed-certs=true 
            --server=https://{{ loadbalancer_ip.stdout }}:6443

        - name: Set admin user credentials
          command: >
            kubectl config set-credentials admin 
            --client-certificate=admin.crt 
            --client-key=admin.key

        - name: Set Kubernetes context
          command: >
            kubectl config set-context kubernetes-the-hard-way 
            --cluster=kubernetes-the-hard-way 
            --user=admin

        - name: Use Kubernetes context
          command: kubectl config use-context kubernetes-the-hard-way

    - name: Verify Kubernetes cluster health
      command: kubectl get componentstatuses
      register: cluster_health

    - name: Display cluster health
      debug:
        msg: "{{ cluster_health.stdout }}"

    - name: List Kubernetes nodes
      command: kubectl get nodes
      register: cluster_nodes

    - name: Display cluster nodes
      debug:
        msg: "{{ cluster_nodes.stdout }}"

